# Generated by Django 3.2.4 on 2021-06-29 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request_Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_received', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField(null=True)),
                ('qualification', models.CharField(max_length=100)),
                ('salary', models.IntegerField(null=True)),
                ('pan_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Response_Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('response', models.CharField(max_length=200)),
                ('response_generated', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FirstAPP.request_info')),
            ],
        ),
    ]
