# Generated by Django 3.2.4 on 2021-06-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response_info',
            name='response_generated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
