# Generated by Django 3.2.4 on 2021-06-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstAPP', '0002_alter_response_info_response_generated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response_Info',
        ),
    ]
