# Generated by Django 3.2.4 on 2021-06-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstAPP', '0002_request_info_request_received'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_received', models.DateTimeField(blank=True, db_column='Request_Received', null=True)),
                ('first_name', models.CharField(blank=True, db_column='First_Name', max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, db_column='Last_Name', max_length=30, null=True)),
                ('middle_name', models.CharField(blank=True, db_column='Middle_Name', max_length=30, null=True)),
                ('dob', models.DateField(blank=True, db_column='DOB', null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=15, null=True)),
                ('nationality', models.CharField(blank=True, db_column='Nationality', max_length=30, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=30, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=30, null=True)),
                ('pincode', models.IntegerField(blank=True, db_column='Pincode', null=True)),
                ('qualification', models.CharField(blank=True, db_column='Qualification', max_length=30, null=True)),
                ('salary', models.IntegerField(blank=True, db_column='Salary', null=True)),
                ('pan_number', models.CharField(blank=True, db_column='PAN_Number', max_length=30, null=True)),
            ],
            options={
                'db_table': 'request_info',
                'managed': False,
            },
        ),
    ]
