# Generated by Django 3.2.4 on 2021-06-29 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirstAPP', '0003_delete_response_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response_Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('response', models.CharField(max_length=200)),
                ('response_generated', models.DateTimeField(auto_now=True)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FirstAPP.request_info')),
            ],
        ),
    ]
