# Generated by Django 3.2.4 on 2021-06-30 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirstAPP', '0004_response_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response_info',
            name='request_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FirstAPP.request_info'),
        ),
    ]
